# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_images_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='slug',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
