# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 04:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_commnents'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commnents',
            new_name='Comments',
        ),
    ]
