# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_auto_20170602_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
